name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: expo/expo-github-action@v6
        with:
          expo-version: '4.x'
          token: ${{ secrets.FDA_API_KEY_FOR_JEM2000 }}
      - run: npm install -g expo-cli
      - run: npm install --save @react-native-community/masked-view
      - run: expo init Food_scanner_and_calorie_counter
      - run: expo install firebase
      - run: expo install expo-barcode-scanner

